apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: backend
spec:
  # type: ClusterIP
  type: LoadBalancer
  ports:
  - port: 2002
    targetPort: 2002
  selector:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: backend